# Project Name
TARGET = FourTrackLooper

# Version Selection - Uncomment ONE of the following lines:
# CPP_SOURCES = FourTrackLooperSimple.cpp      # Minimal version (6 buttons + 5 knobs)
CPP_SOURCES = FourTrackLooper.cpp              # Standard version (10 buttons + 5 knobs)
# CPP_SOURCES = FourTrackLooperAdvanced.cpp    # Full-featured version (20+ controls)
# CPP_SOURCES = FourTrackTapeMachine.cpp       # Tape machine version (15 buttons + 5 knobs)

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
